#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright (c) 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Configuration for the hybrid DIY vacuum agent.
"""


class Config:
    TEACHER_ONLY = True

    GRID_SIZE = 128
    VIEW_SIZE = 21
    LOCAL_VIEW_SIZE = 7

    LOCAL_CHANNELS = 5
    LOCAL_FEATURE_DIM = LOCAL_VIEW_SIZE * LOCAL_VIEW_SIZE * LOCAL_CHANNELS
    GLOBAL_FEATURE_DIM = 26
    FEATURE_DIM = LOCAL_FEATURE_DIM + GLOBAL_FEATURE_DIM
    FEATURE_VECTOR_SHAPE = (FEATURE_DIM,)
    FEATURE_IMAGE_SHAPE = (0,)

    ACTION_DIM = 8
    ACTION_SHAPE = (ACTION_DIM,)
    VALUE_SHAPE = (1,)
    PATH_STYLE_DIM = 5
    MAX_CLEAN_REGION_CANDIDATES = 3
    MAX_EXPLORE_MOUTH_CANDIDATES = 2
    MAX_CHARGER_CANDIDATES = 2
    MAX_DECISION_CANDIDATES = 1 + MAX_CLEAN_REGION_CANDIDATES + MAX_EXPLORE_MOUTH_CANDIDATES + MAX_CHARGER_CANDIDATES + 1
    CANDIDATE_FEATURE_DIM = 28
    CANDIDATE_FLAT_DIM = MAX_DECISION_CANDIDATES * CANDIDATE_FEATURE_DIM
    CANDIDATE_MASK_SHAPE = (MAX_DECISION_CANDIDATES,)
    PATH_STYLE_SHAPE = (PATH_STYLE_DIM,)

    # Planner settings
    REPLAN_INTERVAL = 2
    PLAN_COMMIT_STEPS = 7
    PLAN_PROGRESS_STALL_STEPS = 3
    LOW_BATTERY_RATIO = 0.3
    RETURN_CHARGE_BUFFER = 34
    TARGET_CHARGE_BUFFER = 44
    MAX_TRACKED_PATH = 128
    DIRTY_CLUSTER_RADIUS = 3
    FRONTIER_CLUSTER_RADIUS = 4
    CHARGER_HEURISTIC_SCALE = 1.25
    PATH_FOLLOW_BONUS = 5.2
    SAVE_MODEL_INTERVAL_SEC = 60
    SAMPLE_CHUNK_SIZE = 256
    MAX_VISIT_CLIP = 12
    MAX_TRANSIT_CLIP = 12
    SNAKE_PROGRESS_WEIGHT = 0.42
    SNAKE_BACKTRACK_PENALTY = 0.58
    SNAKE_ACTION_WEIGHT = 1.75
    SNAKE_DIAGONAL_PENALTY = 0.16
    CHARGE_REPEAT_MULTIPLIER = 1.55
    CHARGE_SNAKE_SCALE = 0.55
    CHARGE_EXIT_BATTERY_RATIO = 0.98
    POST_CHARGE_LOCK_STEPS = 16
    POST_CHARGE_HALO_RADIUS = 5
    POST_CHARGE_HALO_PENALTY = 5.2
    POST_CHARGE_OUTWARD_BONUS = 1.15
    CHARGER_LAUNCH_MIN_DIST = 7
    CHARGER_SPOKE_SCAN_RADIUS = 8
    CHARGER_SPOKE_REUSE_PENALTY = 1.35
    CHARGER_SPOKE_ALIGN_WEIGHT = 1.25
    CHARGER_SPOKE_UNVISITED_BONUS = 0.95
    CHARGER_LAUNCH_OUTWARD_WEIGHT = 5.6
    CHARGER_LAUNCH_MONOTONIC_PENALTY = 4.8
    CHARGER_ZONE_REPEAT_VISIT_WEIGHT = 0.10
    CHARGER_ZONE_REPEAT_TRANSIT_WEIGHT = 0.18
    CHARGER_ZONE_REPEAT_DENSITY_WEIGHT = 0.018
    CHARGER_ZONE_REPEAT_GOAL_WEIGHT = 1.25
    CHARGER_ZONE_REPEAT_WALL_SCALE = 0.62
    CHARGER_ZONE_REPEAT_CORNER_SCALE = 1.35
    CHARGER_ZONE_REPEAT_CENTER_SCALE = 0.92
    BOUNDARY_BONUS_WEIGHT = 0.32
    BOUNDARY_ACTION_WEIGHT = 1.1
    BOUNDARY_REPEAT_VISIT_THRESHOLD = 3
    BOUNDARY_REPEAT_TRANSIT_THRESHOLD = 2
    BOUNDARY_NPC_THRESHOLD = 16.0
    GOAL_STICKY_BONUS = 2.4
    REGION_LOCK_DIRTY_RADIUS = 8
    REGION_LOCK_FRONTIER_RADIUS = 10
    REGION_LOCK_VALUE_WEIGHT = 0.38
    REGION_LOCK_STICKY_BONUS = 2.6
    REGION_LOCK_ACTION_WEIGHT = 0.65
    REGION_LOCK_DIRTY_MIN_MASS = 6.0
    REGION_LOCK_FRONTIER_MIN_MASS = 18.0
    EXPLORE_EARLY_RATIO = 0.76
    EXPLORE_SLACK_THRESHOLD = 0.35
    EXPLORE_FRONTIER_GAIN_SCALE = 0.38
    EXPLORE_DISTANCE_RELAX = 0.22
    EXPLORE_REPEAT_RELAX = 0.35
    EXPLORE_BOUNDARY_RELAX = 0.40
    FALLBACK_CHARGE_SLACK = 0.18
    TOPOLOGY_OPEN_RADIUS = 2
    TOPOLOGY_CORRIDOR_OPEN_THRESHOLD = 15
    TOPOLOGY_ROOM_OPEN_THRESHOLD = 19
    TOPOLOGY_SPINE_HALO_RADIUS = 1
    ROOM_REGION_MIN_CELLS = 18
    TAIL_REGION_MIN_DEPTH = 6
    REGION_DIRTY_TRIGGER = 8
    REGION_FRONTIER_TRIGGER = 6
    ACTIVE_REGION_DIRTY_MIN = 3
    ACTIVE_REGION_FRONTIER_MIN = 4
    REGION_MAX_SWITCH_DELAY = 8
    REGION_VALUE_DIRTY_WEIGHT = 1.00
    REGION_VALUE_FRONTIER_WEIGHT = 0.42
    REGION_VALUE_DISTANCE_WEIGHT = 0.18
    REGION_VALUE_RISK_WEIGHT = 0.04
    REGION_VALUE_SPINE_PENALTY = 0.95
    SPINE_DIRTY_PENALTY = 2.8
    SPINE_TRANSIT_BONUS = 0.45
    EXPLORE_MOUTH_BONUS = 5.0
    EXPLORE_ROOM_FRONTIER_BONUS = 1.8
    EXPLORE_CORRIDOR_BOUNDARY_BONUS = 0.65
    CLEAN_REGION_STAY_BONUS = 2.1
    CLEAN_REGION_EXIT_PENALTY = 2.8
    CLEAN_REGION_SWEEP_BONUS = 1.25
    CLEAN_REGION_FAR_PROGRESS = 0.42
    DYNAMIC_RETURN_UNKNOWN_SURCHARGE = 6
    DYNAMIC_RETURN_RISK_SCALE = 0.18
    DYNAMIC_RETURN_REGION_SURCHARGE = 6
    DYNAMIC_RETURN_HEURISTIC_SURCHARGE = 8
    ACTIVE_ROOM_DIRTY_MIN = 1
    ACTIVE_ROOM_FRONTIER_MIN = 1
    ACTIVE_TAIL_DIRTY_MIN = 0
    ACTIVE_TAIL_FRONTIER_MIN = 1
    ACTIVE_REGION_MIN_COMMIT_STEPS = 18
    BRIDGE_REGION_DIRTY_TRIGGER = 14
    BRIDGE_REGION_FRONTIER_TRIGGER = 10
    REGION_ENTRY_CLEAR_RADIUS = 3
    REGION_ENTRY_CLEAR_PENALTY = 1.25
    REGION_ROOM_DIRTY_DENSITY_WEIGHT = 0.28
    REGION_ROOM_FRONTIER_DENSITY_WEIGHT = 0.12
    CLEAN_ROOM_BOUNDARY_SCALE = 0.38
    CLEAN_ROOM_SNAKE_SCALE = 0.48
    CLEAN_ROOM_INTERIOR_BONUS = 0.65
    CLEAN_ROOM_SPINE_EXTRA_PENALTY = 2.6
    CLEAN_REGION_DEEP_STAY_BONUS = 1.2
    CLEAN_REGION_STRONG_EXIT_PENALTY = 4.0
    EXPLORE_BRIDGE_PENALTY = 4.6
    COVER_STRIP_MIN_CELLS = 2
    COVER_TARGET_REFRESH_RADIUS = 1
    COVER_TARGET_WORK_RADIUS = 1
    COVER_SEQUENCE_LOOKAHEAD = 4
    ROOM_SWEEP_PERSIST_BONUS = 2.8
    ROOM_SWEEP_NEXT_STRIP_BONUS = 1.6
    ROOM_SWEEP_REPEAT_PENALTY = 0.75
    BLOCKED_CELL_TTL = 8
    BLOCKED_CELL_PENALTY = 2.2
    NPC_CLEAN_PENALTY = 1.4
    AGGRESSIVE_EDGE_STEPS = 420
    CHARGE_RETRY_MARGIN_SCALE = 0.65
    CHARGE_RETRY_MARGIN_NARROW = 0.9
    CHARGE_RETRY_MARGIN_BLOCKED = 1.1

    # Hierarchical decision policy
    KEEP_PLAN_CANDIDATE_BONUS = 1.2
    DECISION_EVENT_RISK_DELTA = 8.0
    STYLE_POLICY_COEF = 0.55
    STYLE_IMITATION_COEF = 0.35
    STYLE_ENTROPY_COEF = 0.35
    SAFE_RETURN_STYLE_BONUS = 0.9
    DEEP_CLEAN_STYLE_BONUS = 0.7
    AGGRESSIVE_EXPLORE_STYLE_BONUS = 0.5
    ESCAPE_STYLE_BONUS = 0.8
    HL_SCORE_DELTA_REWARD = 0.22
    HL_EFFICIENCY_REWARD = 0.08
    HL_HALO_PENALTY = 0.12
    HL_SPINE_PENALTY = 0.10
    HL_FRONTIER_SKIP_PENALTY = 0.05
    HL_BLOCKED_PENALTY = 0.08
    HL_STUCK_PENALTY = 0.10
    HL_REGION_COMPLETE_REWARD = 0.6

    # NPC risk settings
    NPC_COLLISION_RADIUS = 2
    NPC_PREDICT_RADIUS = 2
    NPC_CENTER_HARD_RADIUS = 4
    NPC_CENTER_SOFT_RADIUS = 12
    NPC_FIELD_SOFTEN = 1.5
    NPC_FIELD_CENTER_SCALE = 120.0
    NPC_FIELD_NPC_SCALE = 90.0
    NPC_FIELD_PRED_SCALE = 72.0
    NPC_FIELD_MID_SCALE = 42.0

    # Reward shaping
    GAMMA = 0.99
    LAMDA = 0.95
    STEP_PENALTY = -0.01
    STUCK_PENALTY = -0.12
    CLEAN_REWARD = 1.15
    CHARGE_REWARD = 0.15
    NPC_DANGER_PENALTY = -0.15
    REPEAT_CLEAN_PENALTY = 0.05
    FRONTIER_REWARD = 0.03

    # Model / optimizer
    HIDDEN_DIM = 192
    INIT_LEARNING_RATE_START = 3e-4
    BETA_START = 0.0015
    CLIP_PARAM = 0.2
    VF_COEF = 0.5
    USE_GRAD_CLIP = True
    GRAD_CLIP_RANGE = 0.5

    # Teacher-student hybrid learning
    IMITATION_COEF_START = 0.65
    IMITATION_COEF_END = 0.05
    IMITATION_DECAY_STEPS = 9000
    TEACHER_MIX_START = 0.28
    TEACHER_MIX_END = 0.00
    TEACHER_MIX_DECAY_STEPS = 1800
    INFER_TEACHER_MIX_FLOOR = 0.00
    INFER_TEACHER_MIX_WARMUP = 0.28
    STUDENT_WARMUP_STEPS = 900
    SAFE_GREEDY_WARMUP_STEPS = 500
    RISK_TEACHER_BIAS = 0.14
    CHARGE_TEACHER_BIAS = 0.08
    STUCK_TEACHER_BIAS = 0.05
    FORCE_TEACHER_RISK = 22.0
    FORCE_TEACHER_STUCK = 2
    CRITICAL_CHARGE_MARGIN = 10
    REWARD_SCALE = 0.35
    FINAL_BONUS_SCALE = 0.35

    CHECKPOINT_TAG = "diy_teacher_guard_v1"
