#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright (c) 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Configuration for the LTSPPO Robot Vacuum agent.
"""

import os


def _env_str(name: str, default: str) -> str:
    value = os.getenv(name)
    if value is None:
        return default
    value = str(value).strip()
    return default if value == "" else value


def _env_float(name: str, default: str) -> float:
    return float(_env_str(name, default))


def _env_int(name: str, default: str) -> int:
    return int(_env_str(name, default))


class Config:
    # ------------------------------------------------------------------
    # Observation layout
    # ------------------------------------------------------------------
    LOCAL_VIEW_SIZE = 21
    LOCAL_VIEW_CHANNELS = 9
    GLOBAL_MEMORY_SIZE = 16
    GLOBAL_MEMORY_CHANNELS = 8

    ENTITY_SLOTS = 8          # 4 NPC + 4 charger
    NPC_SLOTS = 4
    CHARGER_SLOTS = 4
    ENTITY_FEATURE_DIM = 10
    ENTITY_DIM = ENTITY_SLOTS * ENTITY_FEATURE_DIM

    SCALAR_DIM = 128
    ACTION_HISTORY_DIM = 16   # last action one-hot + recent 4-step histogram

    FEATURES = [
        LOCAL_VIEW_CHANNELS * LOCAL_VIEW_SIZE * LOCAL_VIEW_SIZE,
        GLOBAL_MEMORY_CHANNELS * GLOBAL_MEMORY_SIZE * GLOBAL_MEMORY_SIZE,
        ENTITY_DIM,
        SCALAR_DIM,
        ACTION_HISTORY_DIM,
    ]
    FEATURE_SPLIT_SHAPE = FEATURES
    FEATURE_LEN = sum(FEATURES)
    DIM_OF_OBSERVATION = FEATURE_LEN

    # ------------------------------------------------------------------
    # Action / heads
    # ------------------------------------------------------------------
    ACTION_NUM = 8
    MODE_NUM = 6
    ROUTE_ANCHOR_DIM = CHARGER_SLOTS + 1
    TARGET_DIM = CHARGER_SLOTS + 1  # none + top-4 charger candidates
    VALUE_NUM = 1

    LABEL_SIZE_LIST = [ACTION_NUM]
    LEGAL_ACTION_SIZE_LIST = LABEL_SIZE_LIST.copy()

    # ------------------------------------------------------------------
    # Recurrent training
    # ------------------------------------------------------------------
    USE_RECURRENT_POLICY = True
    RNN_HIDDEN_DIM = 192
    SEQ_CHUNK_LEN = 16
    SEQ_BURN_IN = 4
    SEQ_LEARN_LEN = SEQ_CHUNK_LEN - SEQ_BURN_IN
    SEQ_STRIDE = 12

    SAMPLE_OBS_DIM = DIM_OF_OBSERVATION * SEQ_CHUNK_LEN
    SAMPLE_LEGAL_ACTION_DIM = ACTION_NUM * SEQ_CHUNK_LEN
    SAMPLE_ACTION_DIM = SEQ_CHUNK_LEN
    SAMPLE_REWARD_DIM = SEQ_CHUNK_LEN
    SAMPLE_DONE_DIM = SEQ_CHUNK_LEN
    SAMPLE_PROB_DIM = ACTION_NUM * SEQ_CHUNK_LEN
    SAMPLE_MODE_DIM = SEQ_CHUNK_LEN
    SAMPLE_ROUTE_ANCHOR_DIM = SEQ_CHUNK_LEN
    SAMPLE_TARGET_DIM = SEQ_CHUNK_LEN
    SAMPLE_MODE_TEACHER_MASK_DIM = SEQ_CHUNK_LEN
    SAMPLE_ROUTE_ANCHOR_MASK_DIM = SEQ_CHUNK_LEN
    SAMPLE_TARGET_TEACHER_MASK_DIM = SEQ_CHUNK_LEN
    SAMPLE_RETURN_ACTION_DIM = SEQ_CHUNK_LEN
    SAMPLE_RETURN_ACTION_MASK_DIM = SEQ_CHUNK_LEN
    SAMPLE_ROUTE_PHASE_ACTION_DIM = SEQ_CHUNK_LEN
    SAMPLE_ROUTE_PHASE_ACTION_MASK_DIM = SEQ_CHUNK_LEN
    SAMPLE_VALUE_DIM = SEQ_CHUNK_LEN
    SAMPLE_AUX_LABEL_DIM = SEQ_CHUNK_LEN
    SAMPLE_CONSTRAINT_COST_DIM = SEQ_CHUNK_LEN
    EXPERT_WEIGHT_DIM = 1
    FALLBACK_MASK_DIM = SEQ_CHUNK_LEN

    # ------------------------------------------------------------------
    # Model dimensions
    # ------------------------------------------------------------------
    LOCAL_EMBED_DIM = 192
    GLOBAL_EMBED_DIM = 128
    ENTITY_EMBED_DIM = 128
    SCALAR_EMBED_DIM = 96
    ACTION_HISTORY_EMBED_DIM = 32
    FUSED_HIDDEN_DIM = 256
    PRE_RNN_DIM = 192
    TARGET_CONTEXT_DIM = 64
    MODE_EMBED_DIM = 16
    ROUTE_ANCHOR_EMBED_DIM = 16

    # ------------------------------------------------------------------
    # PPO hyperparameters
    # ------------------------------------------------------------------
    GAMMA = 0.99
    LAMDA = 0.95
    INIT_LEARNING_RATE_START = 0.00003
    BETA_START = 0.015
    CLIP_PARAM = 0.15
    VF_COEF = 0.5
    ENTROPY_FLOOR = 0.15
    ENTROPY_FLOOR_COEF = 0.10
    USE_GRAD_CLIP = True
    GRAD_CLIP_RANGE = 0.5
    ADV_CLEAN_CLIP = _env_float("KAIWU_ADV_CLEAN_CLIP", "12.0")
    ADV_SURVIVE_CLIP = _env_float("KAIWU_ADV_SURVIVE_CLIP", "8.0")
    RETURNS_CLEAN_CLIP = _env_float("KAIWU_RETURNS_CLEAN_CLIP", "20.0")
    RETURNS_SURVIVE_CLIP = _env_float("KAIWU_RETURNS_SURVIVE_CLIP", "12.0")
    ADV_NORM_EPS = _env_float("KAIWU_ADV_NORM_EPS", "1e-6")
    ADV_STD_MIN = _env_float("KAIWU_ADV_STD_MIN", "1e-3")
    INVALID_BATCH_CONSECUTIVE_LIMIT = _env_int("KAIWU_INVALID_BATCH_CONSECUTIVE_LIMIT", "20")
    COLLISION_PROCESS_COST_SCALE = _env_float("KAIWU_COLLISION_PROCESS_COST_SCALE", "0.15")
    BATTERY_TERMINAL_COST_SCALE = _env_float("KAIWU_BATTERY_TERMINAL_COST_SCALE", "39.0")

    # Teacher / auxiliary losses
    MODE_TEACHER_WEIGHT = _env_float("KAIWU_MODE_TEACHER_WEIGHT", "0.10")
    ROUTE_ANCHOR_TEACHER_WEIGHT = _env_float("KAIWU_ROUTE_ANCHOR_TEACHER_WEIGHT", "0.08")
    TARGET_TEACHER_WEIGHT = _env_float("KAIWU_TARGET_TEACHER_WEIGHT", "0.10")
    RETURN_ACTION_TEACHER_WEIGHT = _env_float("KAIWU_RETURN_ACTION_TEACHER_WEIGHT", "0.06")
    ROUTE_PHASE_POLICY_TEACHER_WEIGHT = _env_float("KAIWU_ROUTE_PHASE_POLICY_TEACHER_WEIGHT", "0.35")
    AUX_BATTERY_RISK_WEIGHT = 0.05
    AUX_COLLISION_RISK_WEIGHT = 0.05
    TEACHER_FORCE_UNTIL_EPISODE = 160
    TEACHER_ANNEAL_END_EPISODE = 2000
    TEACHER_MIN_SCALE = 0.10
    USE_EXPERT_GRADIENT_ISOLATION = True

    # ------------------------------------------------------------------
    # Reward shaping / observation memories
    # ------------------------------------------------------------------
    ASTAR_POTENTIAL_ALPHA = 0.35
    ASTAR_POTENTIAL_BATTERY_THRESHOLD = 0.88
    TRAJECTORY_LENGTH = 50
    TRAJECTORY_DECAY = 0.02
    ACTION_HISTORY_WINDOW = 4
    RETURN_SLACK_THRESHOLD = _env_float("KAIWU_RETURN_SLACK_THRESHOLD", "4.0")
    PREPARE_RETURN_SLACK_THRESHOLD = _env_float("KAIWU_PREPARE_RETURN_SLACK_THRESHOLD", "6.0")
    PREPARE_RETURN_BATTERY_RATIO = _env_float("KAIWU_PREPARE_RETURN_BATTERY_RATIO", "0.45")
    EXPLORE_REWARD_SCALE = _env_float("KAIWU_EXPLORE_REWARD_SCALE", "0.10")
    EXPLORE_REWARD_CAP = 4.0
    FRONTIER_REWARD_SCALE = _env_float("KAIWU_FRONTIER_REWARD_SCALE", "0.08")
    FRONTIER_LOW_BATTERY_RATIO = 0.35
    FRONTIER_CRITICAL_BATTERY_RATIO = 0.20
    TEACHER_TARGET_STABILITY_WINDOW = 3
    TEACHER_UNKNOWN_PATH_RATIO_MAX = 0.20
    TEACHER_TARGET_MARGIN_MIN = 3.0
    TEACHER_ANCHOR_MARGIN_MIN = 4.0
    TEACHER_RETURN_ACTION_MARGIN_MIN = 1.0

    ORTHOGONAL_MOVE_COST = 1.0
    DIAGONAL_MOVE_COST = 1.0
    DEPART_STEPS = 20
    HARVEST_DIRT_DENSITY = 0.18
    CONTRACT_BATTERY_RATIO = _env_float("KAIWU_CONTRACT_BATTERY_RATIO", "0.24")
    RETURN_BATTERY_RATIO = _env_float("KAIWU_RETURN_BATTERY_RATIO", "0.18")
    CONTRACT_RECOVERABILITY_THRESHOLD = _env_float("KAIWU_CONTRACT_RECOVERABILITY_THRESHOLD", "0.08")
    RETURN_RECOVERABILITY_THRESHOLD = 0.0
    ANCHOR_CONSISTENCY_REWARD = _env_float("KAIWU_ANCHOR_CONSISTENCY_REWARD", "0.04")
    RECOVERABILITY_REWARD_SCALE = _env_float("KAIWU_RECOVERABILITY_REWARD_SCALE", "0.25")
    RETURN_PROGRESS_REWARD_SCALE = _env_float("KAIWU_RETURN_PROGRESS_REWARD_SCALE", "0.35")
    DIAG_EFFICIENCY_REWARD_SCALE = 0.05
    RETURN_STALL_PENALTY = 0.08
    LATE_CONTRACT_PENALTY = 0.35
    RETURN_STALL_BASE_PENALTY = _env_float("KAIWU_RETURN_STALL_BASE_PENALTY", "0.06")
    RETURN_STALL_EMA_SCALE = _env_float("KAIWU_RETURN_STALL_EMA_SCALE", "0.03")

    # Context-aware cleaning / revisit shaping
    CLEANING_RETURN_SCALE = 0.25
    CLEANING_REVISIT_SOFT_SCALE = 0.70
    CLEANING_REVISIT_HARD_SCALE = 0.40
    CLEANING_STALE_BOUNDARY_SCALE = 0.50
    CLEANING_LOOP_SCALE = 0.25
    CLEANING_NARROW_UNKNOWN_SCALE = 0.60
    CLEANING_MISSED_CHARGE_SCALE = 1.0
    CLEANING_SUBOPTIMAL_TARGET_SCALE = 0.60
    FRONTIER_STALE_BOUNDARY_SCALE = 0.25
    DIRTY_APPROACH_STALE_BOUNDARY_SCALE = 0.50

    # Safety / charge-margin shaping
    CHARGE_MARGIN_WARN = _env_float("KAIWU_CHARGE_MARGIN_WARN", "14.0")
    CHARGE_MARGIN_LOW = 10.0
    CHARGE_MARGIN_CRITICAL = 0.0
    CHARGE_MARGIN_WARN_PENALTY = _env_float("KAIWU_CHARGE_MARGIN_WARN_PENALTY", "0.0")
    CHARGE_MARGIN_LOW_PENALTY = _env_float("KAIWU_CHARGE_MARGIN_LOW_PENALTY", "0.03")
    CHARGE_MARGIN_CRITICAL_PENALTY = _env_float("KAIWU_CHARGE_MARGIN_CRITICAL_PENALTY", "0.18")
    MISSED_CHARGE_NEAR_DIST = 1.0
    CHARGER_NEARBY_DIST = 2.0
    MISSED_CHARGE_LOW_BATTERY_RATIO = _env_float("KAIWU_MISSED_CHARGE_LOW_BATTERY_RATIO", "0.40")
    MISSED_CHARGE_SLACK_THRESHOLD = _env_float("KAIWU_MISSED_CHARGE_SLACK_THRESHOLD", "8.0")
    MISSED_CHARGE_PENALTY = _env_float("KAIWU_MISSED_CHARGE_PENALTY", "0.03")
    CHARGER_NEARBY_NOT_CHARGED_PENALTY = _env_float("KAIWU_CHARGER_NEARBY_NOT_CHARGED_PENALTY", "0.02")
    UNKNOWN_PATH_RISK_BATTERY_RATIO = 0.45
    UNKNOWN_PATH_RISK_THRESHOLD = 0.25
    UNKNOWN_PATH_RISK_PENALTY = _env_float("KAIWU_UNKNOWN_PATH_RISK_PENALTY", "0.03")
    NARROW_UNKNOWN_RISK_PENALTY = _env_float("KAIWU_NARROW_UNKNOWN_RISK_PENALTY", "0.02")
    OVERCHARGE_PENALTY_SCALE = _env_float("KAIWU_OVERCHARGE_PENALTY_SCALE", "0.60")
    OVERCHARGE_RATE_THRESHOLD = _env_float("KAIWU_OVERCHARGE_RATE_THRESHOLD", "0.020")
    COVERAGE_EFFICIENCY_BONUS_SCALE = _env_float("KAIWU_COVERAGE_EFFICIENCY_BONUS_SCALE", "0.12")
    COVERAGE_EFFICIENCY_BASELINE = _env_float("KAIWU_COVERAGE_EFFICIENCY_BASELINE", "0.60")
    COVERAGE_TANGLE_PENALTY_SCALE = _env_float("KAIWU_COVERAGE_TANGLE_PENALTY_SCALE", "0.10")
    EDGE_FOLLOW_BONUS_SCALE = _env_float("KAIWU_EDGE_FOLLOW_BONUS_SCALE", "0.06")
    EDGE_FOLLOW_FRONTIER_THRESHOLD = _env_float("KAIWU_EDGE_FOLLOW_FRONTIER_THRESHOLD", "0.10")
    EDGE_FOLLOW_CROSS_COUNT_MAX = _env_float("KAIWU_EDGE_FOLLOW_CROSS_COUNT_MAX", "8.0")
    CHARGER_ACCESS_DISCOVERY_BONUS_SCALE = _env_float("KAIWU_CHARGER_ACCESS_DISCOVERY_BONUS_SCALE", "0.18")
    CHARGER_ACCESS_PROBE_BONUS_SCALE = _env_float("KAIWU_CHARGER_ACCESS_PROBE_BONUS_SCALE", "0.05")
    CHARGER_ACCESS_PROBE_FRONTIER_THRESHOLD = _env_float("KAIWU_CHARGER_ACCESS_PROBE_FRONTIER_THRESHOLD", "0.05")
    CHARGER_ACCESS_PROBE_UNKNOWN_RATIO_MIN = _env_float("KAIWU_CHARGER_ACCESS_PROBE_UNKNOWN_RATIO_MIN", "0.12")
    CHARGER_ACCESS_PROBE_WEAK_ROUTE_MAX = _env_float("KAIWU_CHARGER_ACCESS_PROBE_WEAK_ROUTE_MAX", "1.5")
    CHARGER_ACCESS_PROBE_SLACK_CONFIDENCE_MAX = _env_float("KAIWU_CHARGER_ACCESS_PROBE_SLACK_CONFIDENCE_MAX", "0.50")
    CHARGER_ACCESS_PROBE_CONTRACT_SCALE = _env_float("KAIWU_CHARGER_ACCESS_PROBE_CONTRACT_SCALE", "0.60")
    NPC_PENALTY_SCALE = _env_float("KAIWU_NPC_PENALTY_SCALE", "1.0")
    IDLE_PENALTY_SCALE = _env_float("KAIWU_IDLE_PENALTY_SCALE", "0.02")
    CHARGE_REWARD_BASE = _env_float("KAIWU_CHARGE_REWARD_BASE", "0.60")
    CHARGE_ROUTE_PROGRESS_SCALE = _env_float("KAIWU_CHARGE_ROUTE_PROGRESS_SCALE", "0.18")
    RETURN_PROGRESS_SHAPING_SCALE = _env_float("KAIWU_RETURN_PROGRESS_SHAPING_SCALE", "0.208")
    CONTRACT_ROUTE_PRESSURE_THRESHOLD = _env_float("KAIWU_CONTRACT_ROUTE_PRESSURE_THRESHOLD", "0.65")
    CONTRACT_SOFT_TRIGGER_MIN_HITS = _env_int("KAIWU_CONTRACT_SOFT_TRIGGER_MIN_HITS", "2")
    NECESSARY_CHARGE_BONUS_SCALE = _env_float("KAIWU_NECESSARY_CHARGE_BONUS_SCALE", "1.05")
    UNNECESSARY_CHARGE_PENALTY = _env_float("KAIWU_UNNECESSARY_CHARGE_PENALTY", "0.18")
    CHARGE_DETOUR_COST_SCALE = _env_float("KAIWU_CHARGE_DETOUR_COST_SCALE", "0.045")
    CHARGE_INTERRUPT_COST_SCALE = _env_float("KAIWU_CHARGE_INTERRUPT_COST_SCALE", "0.03")
    SKIP_NEEDED_CHARGE_PENALTY = _env_float("KAIWU_SKIP_NEEDED_CHARGE_PENALTY", "0.22")
    HIGH_NEED_RETURN_STALL_PENALTY = _env_float("KAIWU_HIGH_NEED_RETURN_STALL_PENALTY", "0.12")
    STRONG_HEURISTIC_EVADE_NPC_DISTANCE = _env_float("KAIWU_STRONG_HEURISTIC_EVADE_NPC_DISTANCE", "4.0")
    STRONG_HEURISTIC_RETURN_EXIT_BATTERY_RATIO = _env_float("KAIWU_STRONG_HEURISTIC_RETURN_EXIT_BATTERY_RATIO", "0.85")
    STRONG_HEURISTIC_PRE_RETURN_RECOVERABILITY_THRESHOLD = _env_float("KAIWU_STRONG_HEURISTIC_PRE_RETURN_RECOVERABILITY_THRESHOLD", "0.35")
    STRONG_HEURISTIC_PRE_RETURN_UNKNOWN_RATIO_THRESHOLD = _env_float("KAIWU_STRONG_HEURISTIC_PRE_RETURN_UNKNOWN_RATIO_THRESHOLD", "0.20")
    STRONG_HEURISTIC_PRE_RETURN_ROUTE_PRESSURE_THRESHOLD = _env_float("KAIWU_STRONG_HEURISTIC_PRE_RETURN_ROUTE_PRESSURE_THRESHOLD", "0.50")
    STRONG_HEURISTIC_PRE_RETURN_BIAS_SCALE = _env_float("KAIWU_STRONG_HEURISTIC_PRE_RETURN_BIAS_SCALE", "0.90")
    STRONG_HEURISTIC_RETURN_BIAS_SCALE = _env_float("KAIWU_STRONG_HEURISTIC_RETURN_BIAS_SCALE", "1.80")
    SLICE2_RISK_RELEASE_SCALE = _env_float("KAIWU_SLICE2_RISK_RELEASE_SCALE", "0.28")
    SLICE2_RISK_GROWTH_CLEAN_PENALTY_SCALE = _env_float(
        "KAIWU_SLICE2_RISK_GROWTH_CLEAN_PENALTY_SCALE", "0.22"
    )
    SLICE2_ROUTE_PHASE_RISK_GROWTH_PENALTY_SCALE = _env_float(
        "KAIWU_SLICE2_ROUTE_PHASE_RISK_GROWTH_PENALTY_SCALE", "0.34"
    )
    SLICE2_ROUTE_PHASE_SHADOW_RISK_THRESHOLD = _env_float(
        "KAIWU_SLICE2_ROUTE_PHASE_SHADOW_RISK_THRESHOLD", "0.12"
    )
    SLICE2_CHARGE_OPPORTUNITY_COST_PENALTY_SCALE = _env_float(
        "KAIWU_SLICE2_CHARGE_OPPORTUNITY_COST_PENALTY_SCALE", "0.18"
    )

    # Sticky anchor / target de-biasing
    TARGET_KEEP_SLACK_MIN = 18.0
    TARGET_KEEP_UNKNOWN_RATIO_MAX = 0.35
    TARGET_FORCE_SWITCH_GAP = 6.0
    TARGET_STICKY_GAP_THRESHOLD = 4.0
    TARGET_STICKY_PENALTY = _env_float("KAIWU_TARGET_STICKY_PENALTY", "0.05")
    PLANNER_ALIGNMENT_REWARD = _env_float("KAIWU_PLANNER_ALIGNMENT_REWARD", "0.03")
    PLANNER_DIVERGENCE_PENALTY = _env_float("KAIWU_PLANNER_DIVERGENCE_PENALTY", "0.03")
    PLANNER_CHARGER_EVAL_LIMIT = 3
    TARGET_SELECT_UNKNOWN_COST = 10.0
    TARGET_SELECT_UNREACHABLE_PENALTY = 18.0

    # Reward scale controls for retrain runs
    REWARD_CLEANING_BASE = _env_float("KAIWU_REWARD_CLEANING_BASE", "0.66")
    REWARD_STREAK_BONUS_BASE = _env_float("KAIWU_REWARD_STREAK_BONUS_BASE", "0.07")
    REWARD_CPS_BONUS_SCALE = _env_float("KAIWU_REWARD_CPS_BONUS_SCALE", "0.32")
    REWARD_CPS_BONUS_BASELINE = _env_float("KAIWU_REWARD_CPS_BONUS_BASELINE", "0.58")
    REWARD_CPS_BONUS_SPAN = _env_float("KAIWU_REWARD_CPS_BONUS_SPAN", "0.22")
    EFFECTIVE_COVERAGE_BONUS_SCALE = _env_float("KAIWU_EFFECTIVE_COVERAGE_BONUS_SCALE", "0.18")
    EFFECTIVE_COVERAGE_BONUS_BASELINE = _env_float("KAIWU_EFFECTIVE_COVERAGE_BONUS_BASELINE", "0.72")
    CLEAN_FLOOR_REVISIT_PENALTY_SCALE = _env_float("KAIWU_CLEAN_FLOOR_REVISIT_PENALTY_SCALE", "0.08")
    TARGET_REWARD_ALIGNMENT_ENABLED = _env_str("KAIWU_TARGET_REWARD_ALIGNMENT_ENABLED", "0").strip().lower() in {
        "1", "true", "yes", "on"
    }
    TARGET_CHARGER_ARRIVAL_BONUS_SCALE = _env_float("KAIWU_TARGET_CHARGER_ARRIVAL_BONUS_SCALE", "0.20")
    TARGET_SAFE_RETURN_PROGRESS_BONUS_SCALE = _env_float("KAIWU_TARGET_SAFE_RETURN_PROGRESS_BONUS_SCALE", "0.12")
    TARGET_CLEAN_PER_STEP_EFFICIENCY_BONUS_SCALE = _env_float(
        "KAIWU_TARGET_CLEAN_PER_STEP_EFFICIENCY_BONUS_SCALE", "0.08"
    )
    TARGET_CLEAN_PER_STEP_EFFICIENCY_BASELINE = _env_float(
        "KAIWU_TARGET_CLEAN_PER_STEP_EFFICIENCY_BASELINE", "0.68"
    )
    BATTERY_FAIL_TASK_REWARD_SCALE = _env_float("KAIWU_BATTERY_FAIL_TASK_REWARD_SCALE", "0.28")
    EARLY_BATTERY_FAIL_TASK_REWARD_SCALE = _env_float("KAIWU_EARLY_BATTERY_FAIL_TASK_REWARD_SCALE", "0.10")
    ZERO_CHARGE_BATTERY_FAIL_EXTRA_COST = _env_float("KAIWU_ZERO_CHARGE_BATTERY_FAIL_EXTRA_COST", "0.75")
    REWARD_SCHEDULE_ENABLED = str(os.getenv("KAIWU_REWARD_SCHEDULE_ENABLED", "1") or "1").strip().lower() not in {
        "0", "false", "off", "no"
    }
    REWARD_SCHEDULE_WARM_STEPS = _env_int("KAIWU_REWARD_SCHEDULE_WARM_STEPS", "5000")
    REWARD_SCHEDULE_TOTAL_STEPS = _env_int("KAIWU_REWARD_SCHEDULE_TOTAL_STEPS", "20000")
    NECESSARY_CHARGE_BONUS_SCALE_PEAK = _env_float("KAIWU_NECESSARY_CHARGE_BONUS_SCALE_PEAK", "1.40")
    BATTERY_FAIL_TASK_REWARD_SCALE_PEAK = _env_float("KAIWU_BATTERY_FAIL_TASK_REWARD_SCALE_PEAK", "0.18")
    EARLY_BATTERY_FAIL_TASK_REWARD_SCALE_PEAK = _env_float("KAIWU_EARLY_BATTERY_FAIL_TASK_REWARD_SCALE_PEAK", "0.06")
    REWARD_TOTAL_CLIP = _env_float("KAIWU_REWARD_TOTAL_CLIP", "3.0")
    REWARD_COMPONENT_CLIP = _env_float("KAIWU_REWARD_COMPONENT_CLIP", "3.0")
    EPISODE_COMPLETED_BONUS = _env_float("KAIWU_EPISODE_COMPLETED_BONUS", "6.0")
    EPISODE_BATTERY_FAIL_BONUS = _env_float("KAIWU_EPISODE_BATTERY_FAIL_BONUS", "-12.0")
    EPISODE_COLLISION_FAIL_BONUS = _env_float("KAIWU_EPISODE_COLLISION_FAIL_BONUS", "-16.0")
    EPISODE_UNKNOWN_FAIL_BONUS = _env_float("KAIWU_EPISODE_UNKNOWN_FAIL_BONUS", "-10.0")
    EPISODE_FAIL_EARLY_SCALE = _env_float("KAIWU_EPISODE_FAIL_EARLY_SCALE", "1.2")

    # Constraint-oriented optimization
    BATTERY_SAFE_NEED_THRESHOLD = _env_float("KAIWU_BATTERY_SAFE_NEED_THRESHOLD", "0.12")
    BATTERY_CRITICAL_NEED_THRESHOLD = _env_float("KAIWU_BATTERY_CRITICAL_NEED_THRESHOLD", "0.28")
    BATTERY_FAIL_RATE_TARGET = _env_float("KAIWU_BATTERY_FAIL_RATE_TARGET", "0.08")
    BATTERY_PROCESS_COST_TARGET = _env_float("KAIWU_BATTERY_PROCESS_COST_TARGET", "0.12")
    HIGH_NEED_RETURN_STALL_TARGET = _env_float("KAIWU_HIGH_NEED_RETURN_STALL_TARGET", "0.35")
    COLLISION_FAIL_RATE_TARGET = _env_float("KAIWU_COLLISION_FAIL_RATE_TARGET", "0.03")
    COLLISION_PROCESS_COST_TARGET = _env_float("KAIWU_COLLISION_PROCESS_COST_TARGET", "0.05")

    LAMBDA_BATTERY_INIT = _env_float("KAIWU_LAMBDA_BATTERY_INIT", "0.60")
    LAMBDA_BATTERY_MIN = _env_float("KAIWU_LAMBDA_BATTERY_MIN", "0.60")
    LAMBDA_BATTERY_MAX = _env_float("KAIWU_LAMBDA_BATTERY_MAX", "2.00")
    LAMBDA_BATTERY_UP = _env_float("KAIWU_LAMBDA_BATTERY_UP", "0.06")
    LAMBDA_BATTERY_DOWN = _env_float("KAIWU_LAMBDA_BATTERY_DOWN", "0.005")
    LAMBDA_COLLISION_INIT = _env_float("KAIWU_LAMBDA_COLLISION_INIT", "0.10")
    LAMBDA_COLLISION_MIN = _env_float("KAIWU_LAMBDA_COLLISION_MIN", "0.05")
    LAMBDA_COLLISION_MAX = _env_float("KAIWU_LAMBDA_COLLISION_MAX", "0.60")
    LAMBDA_COLLISION_UP = _env_float("KAIWU_LAMBDA_COLLISION_UP", "0.02")
    LAMBDA_COLLISION_DOWN = _env_float("KAIWU_LAMBDA_COLLISION_DOWN", "0.01")

    # ------------------------------------------------------------------
    # Expert fallback
    # ------------------------------------------------------------------
    EXPERT_BIAS_MIN = 0.0
    EXPERT_BIAS_MAX = 0.0
    EXPERT_ANNEAL_START_EPISODE = 0
    EXPERT_ANNEAL_END_EPISODE = 0
    EXPERT_ANNEAL_MIN_SCALE = 0.0
    EXPERT_EMERGENCY_BATTERY_RATIO = 0.08
    EXPERT_RELIABLE_SLACK_BUFFER = 12.0
    EXPERT_RELIABLE_RETURN_RATIO = 0.45
    EXPERT_RELIABLE_PREPARE_RETURN_RATIO = 0.65

    # ------------------------------------------------------------------
    # Learner runtime tuning
    # ------------------------------------------------------------------
    LEARNER_CPU_THREADS = 4
    LEARNER_CPU_INTEROP_THREADS = 2
    LEARNER_USE_AMP = True
    LEARNER_ALLOW_FOREACH_OPTIMIZER = True
    LEARNER_ALLOW_FUSED_OPTIMIZER = True
    LEARNER_PREFER_BATCH_TENSOR = True
    LEARNER_JIT_TRACE = False
    LEARNER_TORCH_COMPILE = False
    AGENT_LOAD_MODEL_CACHE = True
    AGENT_MIN_RELOAD_STEP_GAP = _env_int("KAIWU_AGENT_MIN_RELOAD_STEP_GAP", "1000")
    AGENT_MIN_RELOAD_INTERVAL_SECONDS = _env_int("KAIWU_AGENT_MIN_RELOAD_INTERVAL_SECONDS", "180")
    AGENT_TRANSITION_GUARD_RELOAD_STEP_GAP = _env_int("KAIWU_AGENT_TRANSITION_GUARD_RELOAD_STEP_GAP", "2000")
    PERF_STAT_WINDOW_SECONDS = 60

    # ------------------------------------------------------------------
    # Dynamic curriculum advancement
    # ------------------------------------------------------------------
    CURRICULUM_WINDOW = 40
    MONITOR_WINDOW = 40
    CURRICULUM_ADVANCE_WIN_RATE = 0.80
    CURRICULUM_ADVANCE_AVG_CS = 800
    CURRICULUM_ADVANCE_CHARGE = 2.5
    CURRICULUM_HOLD_WIN_RATE = 0.70
    CURRICULUM_INITIAL_STAGE = _env_str("KAIWU_CURRICULUM_INITIAL_STAGE", "warmup")
    CURRICULUM_INITIAL_BLEND_FREEZE_STEPS = _env_int("KAIWU_CURRICULUM_INITIAL_BLEND_FREEZE_STEPS", "5000")
    CURRICULUM_RESUME_STABILIZE_STEPS = _env_int("KAIWU_CURRICULUM_RESUME_STABILIZE_STEPS", "8000")
    CURRICULUM_STAGNATION_WARMUP_MIN_STEPS = _env_int("KAIWU_CURRICULUM_STAGNATION_WARMUP_MIN_STEPS", "6000")
    CURRICULUM_STAGNATION_BLEND_MIN_STEPS = _env_int("KAIWU_CURRICULUM_STAGNATION_BLEND_MIN_STEPS", "8000")
    CURRICULUM_STAGNATION_ROBUST_MIN_STEPS = _env_int("KAIWU_CURRICULUM_STAGNATION_ROBUST_MIN_STEPS", "10000")
    CURRICULUM_WARMUP_TIMEOUT_STEPS = _env_int("KAIWU_CURRICULUM_WARMUP_TIMEOUT_STEPS", "25000")
    CURRICULUM_BLEND_TIMEOUT_STEPS = _env_int("KAIWU_CURRICULUM_BLEND_TIMEOUT_STEPS", "35000")
    CURRICULUM_ROBUST_TIMEOUT_STEPS = _env_int("KAIWU_CURRICULUM_ROBUST_TIMEOUT_STEPS", "50000")
    CURRICULUM_BLEND_GUARD_STEPS = _env_int("KAIWU_CURRICULUM_BLEND_GUARD_STEPS", "8000")
    CURRICULUM_ROBUST_GUARD_STEPS = _env_int("KAIWU_CURRICULUM_ROBUST_GUARD_STEPS", "12000")
    CURRICULUM_STAGE_TRANSITION_COOLDOWN_STEPS = _env_int("KAIWU_CURRICULUM_STAGE_TRANSITION_COOLDOWN_STEPS", "8000")
    CURRICULUM_ZERO_CHARGE_FAIL_STRICT_GATE_MAX = _env_float("KAIWU_CURRICULUM_ZERO_CHARGE_FAIL_STRICT_GATE_MAX", "0.15")
    CURRICULUM_ZERO_CHARGE_FAIL_PROFILE_WARN = _env_float("KAIWU_CURRICULUM_ZERO_CHARGE_FAIL_PROFILE_WARN", "0.12")
    CURRICULUM_DEGRADED_MAINLINE_CONFIRM_WINDOWS = _env_int("KAIWU_CURRICULUM_DEGRADED_MAINLINE_CONFIRM_WINDOWS", "2")
    CURRICULUM_LITE_BENCH_ENABLED = _env_str("KAIWU_CURRICULUM_LITE_BENCH_ENABLED", "1").strip().lower() not in {
        "0", "false", "no", "off"
    }
    CURRICULUM_LITE_BENCH_MODE = _env_str("KAIWU_CURRICULUM_LITE_BENCH_MODE", "resume_only").strip().lower()
    CURRICULUM_LITE_BENCH_TIMEOUT_SECONDS = _env_int("KAIWU_CURRICULUM_LITE_BENCH_TIMEOUT_SECONDS", "180")
    CURRICULUM_LITE_BENCH_POLICY_MODE = _env_str("KAIWU_CURRICULUM_LITE_BENCH_POLICY_MODE", "eval").strip().lower()
    CURRICULUM_ADAPTIVE_PROFILE_ENABLED = _env_str("KAIWU_CURRICULUM_ADAPTIVE_PROFILE_ENABLED", "1").strip().lower() not in {
        "0", "false", "no", "off"
    }
    CURRICULUM_OBSERVATION_PHASE_STEPS = _env_int("KAIWU_CURRICULUM_OBSERVATION_PHASE_STEPS", "5000")

    # ------------------------------------------------------------------
    # Training snapshot / resume strategy
    # ------------------------------------------------------------------
    SAVE_MODEL_INTERVAL_EPISODES = 50
    RESUME_LATEST_SYNC_INTERVAL_EPISODES = 20
    RESUME_EPISODE_SNAPSHOT_INTERVAL = 50
    RESUME_STEP_SNAPSHOT_INTERVAL = int(os.getenv("KAIWU_RESUME_STEP_SNAPSHOT_INTERVAL", "6000"))
    RESUME_TIME_SNAPSHOT_INTERVAL_SECONDS = 10 * 60
    KEEP_EPISODE_RESUME_SNAPSHOTS = 16
    KEEP_STEP_RESUME_SNAPSHOTS = int(os.getenv("KAIWU_KEEP_STEP_RESUME_SNAPSHOTS", "80"))
    KEEP_TIME_RESUME_SNAPSHOTS = 48
    KEEP_BEST_RESUME_SNAPSHOTS = 10
    KEEP_PRELOAD_COMPAT_SNAPSHOTS = 5
    USE_LOCAL_RESUME_BOOTSTRAP = False
    TRAINING_START_MODE = os.getenv("KAIWU_TRAINING_START_MODE", "preload").strip().lower()

    RESUME_CHECKPOINT = "/workspace/code/runtime_state/current/prepared_resume/model.pkl"
    TRAINING_BASELINE_CHECKPOINT = os.getenv(
        "KAIWU_TRAINING_BASELINE_CHECKPOINT",
        "/workspace/code/saved_models/v6-geo-bestmodel-576/model.ckpt-resume.pkl",
    )

    # Optional helper for external scripts
    LTSPPO_BRANCH_NAME = os.getenv("KAIWU_LTSPPO_BRANCH_NAME", "linux-LTSPPO")
