#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright (c) 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Monitor panel configuration builder for Robot Vacuum.
"""

from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    monitor = MonitorConfigBuilder()

    config_dict = (
        monitor.title("Robot Vacuum PPO")
        .add_group(group_name="Algorithm", group_name_en="algorithm")
        .add_panel(name="Reward", name_en="reward", type="line")
        .add_metric(metrics_name="reward", expr="avg(reward{})")
        .end_panel()
        .add_panel(name="Total Loss", name_en="total_loss", type="line")
        .add_metric(metrics_name="total_loss", expr="avg(total_loss{})")
        .end_panel()
        .add_panel(name="Value Loss", name_en="value_loss", type="line")
        .add_metric(metrics_name="value_loss", expr="avg(value_loss{})")
        .end_panel()
        .add_panel(name="Policy Loss", name_en="policy_loss", type="line")
        .add_metric(metrics_name="policy_loss", expr="avg(policy_loss{})")
        .end_panel()
        .add_panel(name="Entropy Loss", name_en="entropy_loss", type="line")
        .add_metric(metrics_name="entropy_loss", expr="avg(entropy_loss{})")
        .end_panel()
        .add_panel(name="Avg Episode Steps", name_en="avg_episode_steps", type="line")
        .add_metric(metrics_name="avg_episode_steps", expr="avg(avg_episode_steps{})")
        .end_panel()
        .add_panel(name="Avg Charge Count", name_en="avg_charge_count", type="line")
        .add_metric(metrics_name="avg_charge_count", expr="avg(avg_charge_count{})")
        .end_panel()
        .add_panel(name="Avg Clean Score", name_en="avg_cleaned_cells", type="line")
        .add_metric(metrics_name="avg_cleaned_cells", expr="avg(avg_cleaned_cells{})")
        .end_panel()
        .add_panel(name="Avg Remaining Charge", name_en="avg_remaining_charge", type="line")
        .add_metric(metrics_name="avg_remaining_charge", expr="avg(avg_remaining_charge{})")
        .end_panel()
        .add_panel(name="Invalid Move Rate", name_en="avg_invalid_move_rate", type="line")
        .add_metric(metrics_name="avg_invalid_move_rate", expr="avg(avg_invalid_move_rate{})")
        .end_panel()
        .add_panel(name="Charge Efficiency", name_en="avg_charge_efficiency", type="line")
        .add_metric(metrics_name="avg_charge_efficiency", expr="avg(avg_charge_efficiency{})")
        .end_panel()
        .add_panel(name="Avg Clean Per Step", name_en="avg_clean_per_step", type="line")
        .add_metric(metrics_name="avg_clean_per_step", expr="avg(avg_clean_per_step{})")
        .end_panel()
        .add_panel(name="Battery Fail Rate", name_en="battery_fail_rate", type="line")
        .add_metric(metrics_name="battery_fail_rate", expr="avg(battery_fail_rate{})")
        .end_panel()
        .add_panel(name="Collision Fail Rate", name_en="collision_fail_rate", type="line")
        .add_metric(metrics_name="collision_fail_rate", expr="avg(collision_fail_rate{})")
        .end_panel()
        .add_panel(name="Completed Rate", name_en="completed_rate", type="line")
        .add_metric(metrics_name="completed_rate", expr="avg(completed_rate{})")
        .end_panel()
        .add_panel(name="CPS WIN", name_en="cps_win", type="line")
        .add_metric(metrics_name="cps_win", expr="avg(cps_win{})")
        .end_panel()
        .add_panel(name="Avg Charge Count WIN", name_en="avg_charge_count_win", type="line")
        .add_metric(metrics_name="avg_charge_count_win", expr="avg(avg_charge_count_win{})")
        .end_panel()
        .add_panel(name="Avg Expert Weight", name_en="avg_expert_weight", type="line")
        .add_metric(metrics_name="avg_expert_weight", expr="avg(avg_expert_weight{})")
        .end_panel()
        .add_panel(name="Late Return Rate", name_en="late_return_rate", type="line")
        .add_metric(metrics_name="late_return_rate", expr="avg(late_return_rate{})")
        .end_panel()
        .add_panel(name="Target Switch Rate", name_en="target_switch_rate", type="line")
        .add_metric(metrics_name="target_switch_rate", expr="avg(target_switch_rate{})")
        .end_panel()
        .add_panel(name="Mode Usage Clean", name_en="mode_usage_clean", type="line")
        .add_metric(metrics_name="mode_usage_clean", expr="avg(mode_usage_clean{})")
        .end_panel()
        .add_panel(name="Mode Prep Return", name_en="mode_usage_prepare_return", type="line")
        .add_metric(metrics_name="mode_usage_prepare_return", expr="avg(mode_usage_prepare_return{})")
        .end_panel()
        .add_panel(name="Mode Usage Return", name_en="mode_usage_return", type="line")
        .add_metric(metrics_name="mode_usage_return", expr="avg(mode_usage_return{})")
        .end_panel()
        .add_panel(name="Mode Usage Evade", name_en="mode_usage_evade", type="line")
        .add_metric(metrics_name="mode_usage_evade", expr="avg(mode_usage_evade{})")
        .end_panel()
        .add_panel(name="Anchor WinRate", name_en="anchor_win_rate", type="line")
        .add_metric(metrics_name="anchor_win_rate", expr="avg(anchor_win_rate{})")
        .end_panel()
        .add_panel(name="Mild WinRate", name_en="mild_win_rate", type="line")
        .add_metric(metrics_name="mild_win_rate", expr="avg(mild_win_rate{})")
        .end_panel()
        .add_panel(name="Broad WinRate", name_en="broad_win_rate", type="line")
        .add_metric(metrics_name="broad_win_rate", expr="avg(broad_win_rate{})")
        .end_panel()
        .add_panel(name="Curriculum Stage", name_en="curriculum_stage_idx", type="line")
        .add_metric(metrics_name="curriculum_stage_idx", expr="avg(curriculum_stage_idx{})")
        .end_panel()
        .add_panel(name="Curriculum Progress", name_en="curriculum_progress", type="line")
        .add_metric(metrics_name="curriculum_progress", expr="avg(curriculum_progress{})")
        .end_panel()
        .end_group()
        .build()
    )
    return config_dict
