[env_conf]
# Maps used for training.
map = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Whether to sample a map randomly each episode.
map_random = false

# Number of official robots. Range: 1~4.
robot_count = 4

# Number of charging stations. Range: 1~4.
charger_count = 4

# Maximum steps per episode. Range: 1~2000.
max_step = 2000

# Maximum battery at full charge. Range: 100~999.
battery_max = 200
