#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright (c) 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Configuration for the hybrid DIY vacuum agent.
"""


class Config:
    TEACHER_ONLY = True

    GRID_SIZE = 128
    VIEW_SIZE = 21
    LOCAL_VIEW_SIZE = 7

    LOCAL_CHANNELS = 5
    LOCAL_FEATURE_DIM = LOCAL_VIEW_SIZE * LOCAL_VIEW_SIZE * LOCAL_CHANNELS
    GLOBAL_FEATURE_DIM = 26
    FEATURE_DIM = LOCAL_FEATURE_DIM + GLOBAL_FEATURE_DIM
    FEATURE_VECTOR_SHAPE = (FEATURE_DIM,)
    FEATURE_IMAGE_SHAPE = (0,)

    ACTION_DIM = 8
    ACTION_SHAPE = (ACTION_DIM,)
    VALUE_SHAPE = (1,)

    # Planner settings
    REPLAN_INTERVAL = 2
    LOW_BATTERY_RATIO = 0.3
    RETURN_CHARGE_BUFFER = 34
    TARGET_CHARGE_BUFFER = 44
    EXPLORE_PHASE_STEPS = 560
    MAX_TRACKED_PATH = 128
    FILL_REPLAN_INTERVAL = 8
    REGION_REBUILD_INTERVAL = 18
    REGION_QUEUE_SIZE = 6
    REGION_ENTRY_CANDIDATES = 6
    COVERAGE_TARGET_BATCH = 14
    REGION_SUPPORT_RADIUS = 1
    REGION_TRAVEL_RADIUS = 1
    COVERAGE_DIAGONAL_ACTION_BONUS = 1.55
    COVERAGE_ORTHO_SWITCH_BONUS = 1.10
    COVERAGE_ORTHO_PENALTY = 0.85
    CHARGE_EXIT_STRAIGHT_BONUS = 4.80
    CHARGE_EXIT_DIAGONAL_PENALTY = 2.20
    DIRTY_CLUSTER_RADIUS = 3
    FRONTIER_CLUSTER_RADIUS = 4
    CHARGER_HEURISTIC_SCALE = 1.25
    PATH_FOLLOW_BONUS = 5.2
    SAVE_MODEL_INTERVAL_SEC = 60
    SAMPLE_CHUNK_SIZE = 256
    MAX_VISIT_CLIP = 12
    MAX_TRANSIT_CLIP = 12
    SNAKE_PROGRESS_WEIGHT = 0.42
    SNAKE_BACKTRACK_PENALTY = 0.58
    SNAKE_ACTION_WEIGHT = 1.75
    SNAKE_DIAGONAL_PENALTY = 0.16
    CHARGE_REPEAT_MULTIPLIER = 1.55
    CHARGE_SNAKE_SCALE = 0.55
    BOUNDARY_BONUS_WEIGHT = 0.32
    BOUNDARY_ACTION_WEIGHT = 1.1
    FILL_SNAKE_WEIGHT_SCALE = 0.32
    FILL_BOUNDARY_WEIGHT_SCALE = 0.40
    BOUNDARY_REPEAT_VISIT_THRESHOLD = 3
    BOUNDARY_REPEAT_TRANSIT_THRESHOLD = 2
    BOUNDARY_NPC_THRESHOLD = 16.0
    REGION_LOCK_DIRTY_RADIUS = 8
    REGION_LOCK_FRONTIER_RADIUS = 10
    REGION_LOCK_VALUE_WEIGHT = 0.38
    REGION_LOCK_STICKY_BONUS = 2.6
    REGION_LOCK_ACTION_WEIGHT = 0.65
    REGION_LOCK_DIRTY_MIN_MASS = 6.0
    REGION_LOCK_FRONTIER_MIN_MASS = 18.0
    REGION_PLAN_CANDIDATES = 24
    REGION_SCORE_DIRTY_WEIGHT = 2.4
    REGION_SCORE_FRONTIER_WEIGHT = 2.0
    REGION_SCORE_DISTANCE_WEIGHT = 0.70
    REGION_SCORE_REPEAT_WEIGHT = 0.14
    REGION_SCORE_RISK_WEIGHT = 0.32
    EXPLORE_FRONTIER_ACTION_WEIGHT = 1.85
    EXPLORE_FRONTIER_PATH_WEIGHT = 0.17
    EXPLORE_UNKNOWN_CELL_BONUS = 0.75
    EXPLORE_DIAGONAL_ACTION_BONUS = 0.90
    EXPLORE_DIAGONAL_PATH_BONUS = 0.28
    REGION_VALUE_DIRTY_WEIGHT = 4.2
    REGION_VALUE_FRONTIER_WEIGHT = 2.1
    REGION_VALUE_REPEAT_WEIGHT = 0.14
    REGION_VALUE_RISK_WEIGHT = 0.30
    REGION_TRANSIT_COST_WEIGHT = 1.10
    REGION_TRANSIT_REPEAT_WEIGHT = 0.40
    REGION_TRANSIT_RISK_WEIGHT = 0.22
    COVERAGE_REGION_ACTION_WEIGHT = 1.40
    TRANSIT_REGION_ACTION_WEIGHT = 1.85
    PATH_OVERLAP_WEIGHT = 0.12
    PATH_OVERLAP_TRANSIT_WEIGHT = 0.18
    BOTTLENECK_REPEAT_DISCOUNT = 0.32
    BOTTLENECK_PATH_DISCOUNT = 0.42

    # NPC risk settings
    NPC_COLLISION_RADIUS = 2
    NPC_PREDICT_RADIUS = 2
    NPC_CENTER_HARD_RADIUS = 4
    NPC_CENTER_SOFT_RADIUS = 12
    NPC_FIELD_SOFTEN = 1.5
    NPC_FIELD_CENTER_SCALE = 120.0
    NPC_FIELD_NPC_SCALE = 90.0
    NPC_FIELD_PRED_SCALE = 72.0
    NPC_FIELD_MID_SCALE = 42.0

    # Reward shaping
    GAMMA = 0.99
    LAMDA = 0.95
    STEP_PENALTY = -0.01
    STUCK_PENALTY = -0.12
    CLEAN_REWARD = 1.15
    CHARGE_REWARD = 0.15
    NPC_DANGER_PENALTY = -0.15
    REPEAT_CLEAN_PENALTY = 0.05
    FRONTIER_REWARD = 0.03

    # Model / optimizer
    HIDDEN_DIM = 192
    INIT_LEARNING_RATE_START = 3e-4
    BETA_START = 0.0015
    CLIP_PARAM = 0.2
    VF_COEF = 0.5
    USE_GRAD_CLIP = True
    GRAD_CLIP_RANGE = 0.5

    # Teacher-student hybrid learning
    IMITATION_COEF_START = 0.65
    IMITATION_COEF_END = 0.05
    IMITATION_DECAY_STEPS = 9000
    TEACHER_MIX_START = 0.28
    TEACHER_MIX_END = 0.00
    TEACHER_MIX_DECAY_STEPS = 1800
    INFER_TEACHER_MIX_FLOOR = 0.00
    INFER_TEACHER_MIX_WARMUP = 0.28
    STUDENT_WARMUP_STEPS = 900
    SAFE_GREEDY_WARMUP_STEPS = 500
    RISK_TEACHER_BIAS = 0.14
    CHARGE_TEACHER_BIAS = 0.08
    STUCK_TEACHER_BIAS = 0.05
    FORCE_TEACHER_RISK = 22.0
    FORCE_TEACHER_STUCK = 2
    CRITICAL_CHARGE_MARGIN = 10
    REWARD_SCALE = 0.35
    FINAL_BONUS_SCALE = 0.35

    CHECKPOINT_TAG = "diy_teacher_guard_v1"
