version: '3.8'

services:
  pushgateway:
    restart: "no"

  backup_model:
    restart: "no"

  learner:
    restart: "no"
    environment:
      KAIWU_BENCHMARK_PARALLEL_MODE: ${KAIWU_BENCHMARK_PARALLEL_MODE:-}
      KAIWU_BENCHMARK_SESSION_ID: ${KAIWU_BENCHMARK_SESSION_ID:-}
      KAIWU_BENCHMARK_RUNTIME_DIR: ${KAIWU_BENCHMARK_RUNTIME_DIR:-}
      KAIWU_BENCHMARK_CHECKPOINT: ${KAIWU_BENCHMARK_CHECKPOINT:-}
      KAIWU_BENCHMARK_WORKER_COUNT: ${KAIWU_BENCHMARK_WORKER_COUNT:-}
      KAIWU_BENCHMARK_ENVS_PER_WORKER: ${KAIWU_BENCHMARK_ENVS_PER_WORKER:-}
      KAIWU_BENCHMARK_SCHEDULER: ${KAIWU_BENCHMARK_SCHEDULER:-}
      KAIWU_BENCHMARK_RESULTS_FILE: ${KAIWU_BENCHMARK_RESULTS_FILE:-}

  aisrv:
    restart: "no"
    environment:
      KAIWU_BENCHMARK_PARALLEL_MODE: ${KAIWU_BENCHMARK_PARALLEL_MODE:-}
      KAIWU_BENCHMARK_SESSION_ID: ${KAIWU_BENCHMARK_SESSION_ID:-}
      KAIWU_BENCHMARK_RUNTIME_DIR: ${KAIWU_BENCHMARK_RUNTIME_DIR:-}
      KAIWU_BENCHMARK_CHECKPOINT: ${KAIWU_BENCHMARK_CHECKPOINT:-}
      KAIWU_BENCHMARK_WORKER_COUNT: ${KAIWU_BENCHMARK_WORKER_COUNT:-}
      KAIWU_BENCHMARK_ENVS_PER_WORKER: ${KAIWU_BENCHMARK_ENVS_PER_WORKER:-}
      KAIWU_BENCHMARK_SCHEDULER: ${KAIWU_BENCHMARK_SCHEDULER:-}
      KAIWU_BENCHMARK_RESULTS_FILE: ${KAIWU_BENCHMARK_RESULTS_FILE:-}

  gamecore:
    restart: "no"
